### ISSUE TITLE
Get the results raw values

### ISSUE THREAD

**Issue by synw** [lesnitsky/perf_timer#2]
It could be nice to have a possibility to get the non formatted raw results in the form of a map. For example I want to time a query and I don't need the total. I suggest that `report` gives the raw results, and to make another function to get the formatted results. I think this function should also print by itself because it does not make much sense to get the formatted results for anything other than printing: I suggest `printReport`

**Comment by lesnitsky** [comment]
Makes perfect sense
Feel free to contribute

**Comment by synw** [comment]
I checked the code and it is not super clear to me yet, your style of coding being very different from mine. It appears that a refactor is needed to be able to get this feature. Could you please just separate the calculations parts from the reporting part, isolating a function that returns a results map? It would be better if you do the heavy lifting on that part please.

I have specific questions about some parts of the code that I will ask later

**Comment by synw** [comment]
This feature is not really needed: using `Stopwatch` for simple cases works well, closing.
